name: TWxCore
main: net.boutopia.ToolWorx.TWxCore.TWxCore
version: 0.1a

commands:
   TW:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.TW
      permission-message: You don't have <permission>